# Generated by Django 6.0.5 on 2026-05-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
